services:
  mongodb:
    image: mongo:7
    container_name: task-manager-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - task_manager_data:/data/db

volumes:
  task_manager_data:
